- name: model distribution
  hosts: all
  vars:
    registry: "123.214.186.252:39500"
    image_name: "{{ ansible_facts['architecture'] }}-model"
    model_tag: "imagenet"

  tasks:

  - name: get model image from server
    tags: distrb
    shell: docker pull {{ registry }}/{{ image_name }}:{{ model_tag }}
    register: output
  - debug: msg="{{ output.stdout_lines }}"
    tags: distrb

  - name: create new container
    tags: distrb
    shell: docker run -d --name model -it {{ registry }}/{{ image_name }}:{{ model_tag }}
    register: output
  - debug: msg="{{ output.stdout_lines }}"
    tags: distrb

  - name: get image list
    tags: search
    shell: docker images
    register: output
  - debug: msg="{{ output.stdout_lines }}"
    tags: search

  - name: get container list
    tags: search
    shell: docker ps -a
    register: output
  - debug: msg="{{ output.stdout_lines }}"
    tags: search