- name: Docker model run && show output
  hosts: all
  
  # vars_prompt:
  #   - name: tag
  #     prompt: please enter the type of model.
  #     private: no
  
  vars:
    image_name: "{{ ansible_facts['architecture'] }}-model"
    model_tag: "imagenet"
    input: "test.jpg"
    server_ip: keti@ketiabcs.iptime.org

  
  tasks:

  ## run container
  # - name: run container
  #   command: docker run -d --name model -it {{ image_name }}:{{ model_tag }}
  #   register: command_output
  # - debug:
  #     var: command_output.stdout_lines


  ## get input
  - name: input from server to node
    tags: input
    copy:
      src: "/var/www/html/tmp/{{ input }}"
      dest: data/

  - name: input from node to model container
    tags: input
    command: docker cp data/{{ input }} model:/home/data/
    register: command_output
  - debug: msg="{{command_output.stdout_lines}}"
    tags: input



  ## run model
  - name: model prediction
    tags: pred
    command: docker exec model python home/model.py --input {{ input }}
    register: command_output
  - debug: msg="{{command_output.stdout_lines}}"
    tags: pred




