version: '3'
 
services:
    php:
        build:
            context: ./config/php
        ports:
            - 9000:9000
        volumes:
            - ./web:/var/www/html
            - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD}
        depends_on:
            - db
        links:
            - db
 
    nginx:
        image: nginx:1.17
        ports:
            - 81:80
        volumes:
            - ./web:/var/www/html
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_USER_PASSWORD}"
        ports:
            #- ${IP}:8000:80 # 보안 강력 (실제 서비스에 적용)
            - 8000:80 # 임시
        links:
            - db:db

    db:
        image: mysql:latest    
        ports:
            #- ${IP}:3300:3306 # 보안 강력 (실제 서비스에 적용) 
            - 3300:3306 # 임시로 '${IP}:' 헤더를 제거
        command: "mysqld --init-file /data/application/init.sql"
        volumes:
            - ./data/init.sql:/data/application/init.sql
            #- db_data:/var/lib/mysql # volume
            - /home/jpark/.evc/mariadb:/var/lib/mysql # maridadb data
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
            
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
          - ./config/prometheus:/etc/prometheus
          - ~/.evc/prometheus:/prometheus
        ports:
          - 9090:9090 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
        command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
          - '--web.enable-lifecycle'
          - '--config.file=/etc/prometheus/prometheus.yml'
        restart: always
        networks:
          - promnet
        user: "$UID:$GID"

    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        # user: "$GRA_UID:$GRA_GID"
        ports:
          - 3000:3000 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
        volumes:
          - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
          - ~/.evc/grafana:/var/lib/grafana
        restart: always    
        environment:
          - GF_SERVER_ROOT_URL=http://evc.re.kr/
          - GF_INSTALL_PLUGINS=grafana-clock-panel
        networks:
          - promnet
        user: "$UID:$GID"

volumes:
    db_data:

networks:
  promnet:
    driver: bridge