- name: copy CA files & keys
  hosts: all
  tags: https
  become: true
  vars:
    host_name: keti
    registry: 123.214.186.252:39500
    ansible_sudo_pass: ketiabcs

  tasks:

    - name: copy registry CA from server to node
      copy:
        src: "/home/keti/certs/registry.crt"
        dest: "/home/{{ host_name }}/"

    - name: register CA keys step 1
      command: cp registry.crt /usr/local/share/ca-certificates/registry.crt
      register: output
    - debug: msg="{{output.stdout_lines}}"
    
    - name: register CA keys step 2
      command: echo registry.crt | sudo tee -a /etc/ca-certificates.conf
      register: output
    - debug: msg="{{output.stdout_lines}}"
    
    - name: register CA keys step 3
      command: update-ca-certificates
      register: output
    - debug: msg="{{output.stdout_lines}}"
    
    - name: register CA keys step 4
      command: sudo systemctl restart docker
      register: output
    - debug: msg="{{output.stdout_lines}}"

    - name: Registry connection test
      command : curl -k https://{{ registry }}/v2/_catalog
      register: output
    - debug: msg="{{output.stdout_lines}}"




- name: insecure-registry config update
  hosts: all
  tags: http
  become: true
  vars:
    host_name: keti
    registry: deepcase.mynetgear.com:20093
    ansbile_sudo_pass: ketiabcs

  tasks:

    - name: configuration update
      become: true
      become_user: root
      copy: 
        content: |
          {"insecure-registries":["deepcase.mynetgear.com:20093"]}
        dest: "/etc/docker/daemon.json"

    - name: restart docker demon
      command: sudo systemctl restart docker
      register: output
    - debug: msg="{{ output.stdout_lines }}"

    - name: connection test
      command: docker pull deepcase.mynetgear.com:20093/hello-world:test
      register: output
    - debug: msg="{{ output.stdout_lines }}"