- name: cmd test
  hosts: builders
  
  vars_prompt:
    - name: tag
      prompt: please enter the type of model.
      private: no
  
  vars:
    image_name: "{{ ansible_facts['architecture'] }}-model"
    registry_ip: 192.168.1.18:5000

  tasks:

  ## build new model image
  - name: cpu-arch detection
    debug:
      msg: cpu architecture is {{ ansible_facts['architecture'] }}
  - name: build test
    command: docker build --tag {{ image_name }}:{{ tag }} dockerfile/
    register: command_output
  - debug:
      var: command_output.stdout_lines
  

  ## run container & test model
  - name: run container
    command: docker run -d --name model -it {{ image_name }}:{{ tag }}
    register: command_output
  - debug:
      var: command_output.stdout_lines
  - name: model prediction test
    command: docker exec model python home/classifier.py --input test.jpg
    register: command_output
  - debug:
      var: command_output.stdout_lines
  

  ## rename & push model image
  - name: rename model image...
    command: docker tag {{ image_name }}:{{ tag }} {{ registry_ip }}/{{ image_name }}{{ tag }}
    register: command_output
  - debug:
      var: command_output.stdout_line
  - name: push image...
    command: docker push {{ registry_ip }}/{{ image_name }}:{{ tag }}
    register: command_output
  - debug:
      var: command_output.stdout_lines
  - name: check result...
    command: 
      curl -X GET http://{{ registry_ip }}/v2/_catalog
      curl -X GET http://{{ registry_ip }}/v2/{{ image_name }}/tags/list
    register: command_output
  - debug:
      var: command_output.stdout_lines